name: sample_dbt_project
version: '1.0'
config-version: 2
profile: snowflake_profile

source-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
data-paths:
  - data
macro-paths:
  - macros
seed-paths:
  - seeds

models:
  sample_dbt_project:
    +materialized: view
    vs_customer:
      +materialized: table
      +database: analytics
      +schema: vscode_data
