sample_dbt_profile:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: sample.db

snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: KAKFMVM-PBB25736.us-west-2
      user: VIVEK8197
      password: Snowflake@8197339944
      role: SYSADMIN
      database: analytics
      warehouse: COMPUTE_WH
      schema: vscode_data
      threads: 1
