sample_dbt_profile:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: sample.db

snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: KAKFMVM-PBB25736
      user: VIVEK8197
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: your_role       # Replace with your role
      database: analytics
      warehouse: your_warehouse  # Replace with your warehouse
      schema: vscode_data
      threads: 1
